### ISSUE TITLE
Color does not work for thin edges

### ISSUE THREAD

**Issue by ugroempi** [gaborcsardi/sankey#2]
Hi Gabor,

function curveseg does not use the color for drawing lines, which is really detrimental for thin edges. Here is a proposed fix (last two lines in the function):

`lines(c(xx[i], xx[i + 1]), c(yy[i], yy[i + 1]), lty = lty, col=grad[i])`
`lines(c(xx[i], xx[i + 1]), c(yy[i] + w, yy[i + 1] + w), lty = lty, col=grad[i])`

Best, Ulrike

**Comment by gaborcsardi** [comment]
Thanks! Would you like to submit a pull request?

**Comment by ugroempi** [comment]
I didn't ever do one, so I'd rather not :-)

Am 16.11.2017 um 21:17 schrieb Gábor Csárdi:

**Comment by gaborcsardi** [comment]
OK. There is a always a first time. :) https://www.youtube.com/watch?v=YTbRzhQju4c

**Comment by ugroempi** [comment]
Indeed. It was pretty straightforward :-)

**Comment by gaborcsardi** [comment]
Fixed by #3
